#!/usr/bin/env sh

echo "▶ lint"
pnpm lint || { echo "✗ lint failed"; exit 1; }

echo "▶ type-check"
pnpm type-check || { echo "✗ type-check failed"; exit 1; }

echo "▶ build"
pnpm build || { echo "✗ build failed"; exit 1; }
